# The west manifest file (west.yml) for the Alif SDK.
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# See the west documentation for more information:
# https://docs.zephyrproject.org/latest/develop/west/index.html

manifest:
  version: "0.13"

  defaults:
    remote: alif

  remotes:
    - name: alif
      url-base: https://github.com/alifsemi
    # Other repository sources:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: armmbed
      url-base: https://github.com/ARMmbed
  
  #
  # Please add items below based on alphabetical order
  projects:

    - name: zephyr
      repo-path: alif_zephyr
      revision: alif_v3.3
      import:
        # In addition to the zephyr repository itself, 
        # Alif SDK fetches the needed projects 
        #
        # Please keep this list sorted alphabetically.
        name-allowlist:
          - canopennode
          - chre
          - cmsis
          - edtt
          - fatfs
          - hal_alif.git
          - liblc3
          - libmetal
          - littlefs
          - lvgl
          - lz4
          - mbedtls
          - mipi-sys-t
          - nanopb
          - net-tools
          - openthread
          - picolibc
          - psa-arch-tests
          - segger
          - tinycrypt
          - tf-m-tests
          - tflite-micro
          - TraceRecorderSource
          - uoscore-uedhoc
          - zcbor
          - zscilib

    - name: hal_alif
      repo-path: hal_alif
      path: modules/hal/alif
      revision: alif_v3.3

    - name: hal_ethos_u
      revision: 90ada2ea5681b2a2722a10d2898eac34c2510791
      path: modules/hal/ethos_u
      remote: zephyrproject
      groups:
        - hal

  self:
    path: alif
    west-commands: scripts/west-commands.yml

